export const headers = [
  {
    image: 'assets/avatars/headers/boy1.svg',
    scale: 1.03,
    top: 3,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy2.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy3.svg',
    scale: 1,
    top: -6,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy4.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy5.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy6.svg',
    scale: 1.03,
    top: 4,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy7.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy8.svg',
    scale: 1,
    top: -5,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy9.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy10.svg',
    scale: 1.03,
    top: 4,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy11.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/boy12.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl1.svg',
    scale: 1,
    top: -7,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl2.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl3.svg',
    scale: 1,
    top: 5,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl4.svg',
    scale: 1,
    top: 1,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl5.svg',
    scale: 1,
    top: 4,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl6.svg',
    scale: 1,
    top: 6,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl7.svg',
    scale: 1.1,
    top: 1,
    left: -10,
  },
  {
    image: 'assets/avatars/headers/girl8.svg',
    scale: 1,
    top: -4,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl9.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl10.svg',
    scale: 1.1,
    top: 1,
    left: 0,
  },
  {
    image: 'assets/avatars/headers/girl12.svg',
    scale: 1.1,
    top: 5,
    left: 0,
  },
];
export const bodies = [
  {
    image: 'assets/avatars/bodies/tshirt1.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/bodies/tshirt2.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/bodies/tshirt3.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/bodies/tshirt4.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/bodies/tshirt5.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/bodies/tshirt6.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
];
export const footers = [
  {
    image: 'assets/avatars/footers/pants1.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/pants2.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/pants3.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/pants4.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/pants5.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/pants6.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/pants7.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/pants8.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt1.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt2.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt3.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt4.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt5.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt6.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt7.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt8.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/footers/skirt9.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
];
export const accessories = [
  {
    image: 'assets/avatars/accessories/baseball.svg',
    scale: 0.95,
    top: -30,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/astronayut.svg',
    scale: 1.1,
    top: -8,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/bow.svg',
    scale: 0.9,
    top: -30,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/cat_ears.svg',
    scale: 0.87,
    top: -52,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/cat_hat.svg',
    scale: 1.09,
    top: -30,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/cocodrile_hat.svg',
    scale: 1.09,
    top: -30,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/hats.svg',
    scale: 1.09,
    top: -48,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/hats1.svg',
    scale: 1.09,
    top: -48,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/helmet.svg',
    scale: 1,
    top: -60,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/king.svg',
    scale: 1,
    top: -50,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/ninja.svg',
    scale: 1,
    top: -20,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/penguin_hat.svg',
    scale: 0.8,
    top: -60,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/pirate.svg',
    scale: 1.1,
    top: -30,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/red_hay.svg',
    scale: 0.8,
    top: -60,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/summer_hat.svg',
    scale: 1,
    top: -50,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/sunglasses.svg',
    scale: 0.56,
    top: 6,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/super_hero.svg',
    scale: 1,
    top: 0,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/viking.svg',
    scale: 1.17,
    top: -55,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/winter_hat.svg',
    scale: 0.82,
    top: -60,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/witch_hat.svg',
    scale: 1.1,
    top: -90,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/fire.svg',
    scale: 1.15,
    top: -66,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/fly.svg',
    scale: 1.04,
    top: -25,
    left: 0,
  },
  {
    image: 'assets/avatars/accessories/glasses.svg',
    scale: 0.56,
    top: 6,
    left: 0,
  },
];
