export const AVATAR_SET_DATA = 'AVATAR_SET_DATA';
export const AVATAR_RESET = 'AVATAR_SET_RESET';
export const AVATAR_SET_ACCESORY = 'AVATAR_SET_ACCESORY';
export const AVATAR_SET_HEAD = 'AVATAR_SET_HEAD';
export const AVATAR_SET_BODY = 'AVATAR_SET_BODY';
export const AVATAR_SET_FOOTERS = 'AVATAR_SET_FOOTERS';
