export const EARNING_SET_DATA = 'EARNING_SET_DATA';
export const EARNING_RESET = 'EARNING_SET_RESET';
export const EARNING_ENERGY_UP = 'EARNING_ENERGY_UP';
export const EARNING_ENERGY_SET = 'EARNING_ENERGY_SET';
export const EARNING_ENERGY_RESET = 'EARNING_ENERGY_RESET';
