export const STUDENT_GET_COLLECTIBLE = 'STUDENT_GET_COLLECTIBLE';
export const STUDENT_ANSWERS_BLOCK = 'STUDENT_ANSWERS_BLOCK';
export const STUDENT_ANSWERS_QUESTION = 'STUDENT_ANSWERS_QUESTION';
export const STUDENT_ADD_AVATAR = 'STUDENT_ADD_AVATAR';
export const STUDENT_REMOVE_AVATAR = 'STUDENT_REMOVE_AVATAR';
export const STUDENT_AUTH = 'STUDENT_AUTH';
export const STUDENT_SELECT_CARD = 'STUDENT_SELECT_CARD';
export const STUDENT_CLOSE_CARD = 'STUDENT_CLOSE_CARD';
export const STUDENT_SELECT_TYPE_GAME = 'STUDENT_SELECT_TYPE_GAME';
export const STUDENT_SELECT_GAME = 'STUDENT_SELECT_GAME';
export const STUDENT_CLOSE_GAME = 'STUDENT_CLOSE_GAME';
export const STUDENT_SELECT_TOPIC = 'STUDENT_SELECT_TOPIC';
export const STUDENT_CONFIG = 'STUDENT_CONFIG';
export const STUDENT_SET_DATA = 'STUDENT_SET_DATA';
export const STUDENT_RESET = 'STUDENT_SET_RESET'

